### ISSUE TITLE
If RFC doesn't exist...

### ISSUE THREAD

**Issue by ross-spencer** [exponential-decay/rfc-du-jour#1]
```
  RFC: 4700 does not exist.
  Traceback (most recent call last):
    File "rfcdujour/rfc-du-jour.py", line 282, in <module>
      main()
    File "rfcdujour/rfc-du-jour.py", line 277, in main
      newtweet = newRFC(twitter)
    File "rfcdujour/rfc-du-jour.py", line 269, in newRFC
      tweet = makeTweet(rfcnumber)
    File "rfcdujour/rfc-du-jour.py", line 247, in makeTweet
      parser = returnRFCHTML(rfcnumber)
    File "rfcdujour/rfc-du-jour.py", line 145, in returnRFCHTML
      response = returnURL(req, True, rfcnumber)
    File "rfcdujour/rfc-du-jour.py", line 127, in returnURL
      returnRFCHTML(rfcToTweet(minRFC, maxRFC))
  NameError: global name 'minRFC' is not defined

  2015-12-07 09:03:29 -- Completed task, took 61.00 seconds, return code was 1.
```

**Comment by ross-spencer** [comment]
Fixed by https://github.com/exponential-decay/rfc-du-jour/commit/85316b2da9c7b3f59e003b2f43f7926ae3090c0e
